### ISSUE TITLE
CONSUMET CLOSED??

### ISSUE THREAD

**Issue by chitrakshbotwala** [Luckyhv/aniplay#20]
consumet aint working i get errors 
468-bf689489822e72f4.js:1 Error fetching Consumet Episodes: TypeError: Failed to fetch
    at a (673-57960c704176eb68.js:1:8445)
    at e (page-fa621d1e4edb4196.js:1:6464)
    at page-fa621d1e4edb4196.js:1:6698
    at aI (fd9d1056-a8de44a064d1f829.js:1:72857)
    at a3 (fd9d1056-a8de44a064d1f829.js:1:84298)
    at a5 (fd9d1056-a8de44a064d1f829.js:1:84936)
    at a8 (fd9d1056-a8de44a064d1f829.js:1:84820)
    at a5 (fd9d1056-a8de44a064d1f829.js:1:84916)
    at a8 (fd9d1056-a8de44a064d1f829.js:1:84820)
    at a5 (fd9d1056-a8de44a064d1f829.js:1:85881)

**Comment by Luckyhv** [comment]
Are u using the latest consumet.
It's updated recently

**Comment by chitrakshbotwala** [comment]
I'm using the latest version if it was not updated within the last 1 hour its the latest version am using

**Comment by chitrakshbotwala** [comment]
<img width="516" alt="image" src="https://github.com/Luckyhv/aniplay/assets/68012660/ab1d2faa-5cff-4e81-a7e1-60e19cb50cd4">

**Comment by Luckyhv** [comment]
It looks like a cors issue
Join discord I will help u or u can dm me personally

**Comment by chitrakshbotwala** [comment]
If you could give me your discord I'd we could join in a vc and talk about
it

**Comment by Luckyhv** [comment]
here u go
https://discord.gg/aW5P4W94ZS
