### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by flawsom** [Luckyhv/aniplay#5]
gitpod /workspace/aniplay (master) $ yarn start
yarn run v1.22.21
$ next start
   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000

 ✓ Ready in 808ms
Error fetching episode history by epid Error: Failed to get Episode
    at w (/workspace/aniplay/.next/server/app/anime/watch/[[...watchid]]/page.js:1:240981)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async S (/workspace/aniplay/.next/server/app/anime/watch/[[...watchid]]/page.js:1:242135)

![Screenshot (15)](https://github.com/Luckyhv/aniplay/assets/64182228/62336e8b-3389-40fa-8ad1-1d54b7f3cc17)

and as a result of this the videos wont actually play, they won't even load...

**Comment by Luckyhv** [comment]
Use the command `yarn run dev` to start the page it will then play the video.
